name: CreateRelease

on:
  push:
    tags:
      - "v*"
 
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore packages
      run: nuget restore PluginDemos.sln
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build with MSBuild
      run: msbuild  PluginDemos.sln -p:Configuration=Release
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      shell: bash
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: GMDC Plugin Demos ${{ github.ref }}
        body: GMDC Plugin Demos ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: true
    - name: Upload Assets to Release with a wildcard
      uses: csexton/release-asset-action@v2
      with:
        pattern: "Publish/*"
        github-token: ${{ secrets.GITHUB_TOKEN }}
        release-url: ${{ steps.create_release.outputs.upload_url }}